//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17626.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class omf {
    
    private omfOpenmenu openmenuField;
    
    private omfRestaurant_info restaurant_infoField;
    
    private omfMenu[] menusField;
    
    private string uuidField;
    
    private System.DateTime created_dateField;
    
    private byte accuracyField;
    
    /// <remarks/>
    public omfOpenmenu openmenu {
        get {
            return this.openmenuField;
        }
        set {
            this.openmenuField = value;
        }
    }
    
    /// <remarks/>
    public omfRestaurant_info restaurant_info {
        get {
            return this.restaurant_infoField;
        }
        set {
            this.restaurant_infoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("menu", IsNullable=false)]
    public omfMenu[] menus {
        get {
            return this.menusField;
        }
        set {
            this.menusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uuid {
        get {
            return this.uuidField;
        }
        set {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime created_date {
        get {
            return this.created_dateField;
        }
        set {
            this.created_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte accuracy {
        get {
            return this.accuracyField;
        }
        set {
            this.accuracyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfOpenmenu {
    
    private decimal versionField;
    
    private omfOpenmenuCrosswalks crosswalksField;
    
    /// <remarks/>
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public omfOpenmenuCrosswalks crosswalks {
        get {
            return this.crosswalksField;
        }
        set {
            this.crosswalksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfOpenmenuCrosswalks {
    
    private omfOpenmenuCrosswalksCrosswalk crosswalkField;
    
    /// <remarks/>
    public omfOpenmenuCrosswalksCrosswalk crosswalk {
        get {
            return this.crosswalkField;
        }
        set {
            this.crosswalkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfOpenmenuCrosswalksCrosswalk {
    
    private string crosswalk_idField;
    
    private string crosswalk_companyField;
    
    private string crosswalk_urlField;
    
    /// <remarks/>
    public string crosswalk_id {
        get {
            return this.crosswalk_idField;
        }
        set {
            this.crosswalk_idField = value;
        }
    }
    
    /// <remarks/>
    public string crosswalk_company {
        get {
            return this.crosswalk_companyField;
        }
        set {
            this.crosswalk_companyField = value;
        }
    }
    
    /// <remarks/>
    public string crosswalk_url {
        get {
            return this.crosswalk_urlField;
        }
        set {
            this.crosswalk_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfRestaurant_info {
    
    private string restaurant_nameField;
    
    private string business_typeField;
    
    private object brief_descriptionField;
    
    private object full_descriptionField;
    
    private object location_idField;
    
    private object mobileField;
    
    private decimal longitudeField;
    
    private decimal latitudeField;
    
    private object utc_offsetField;
    
    private string address_1Field;
    
    private string address_2Field;
    
    private string city_townField;
    
    private string state_provinceField;
    
    private ushort postal_codeField;
    
    private string countryField;
    
    private object region_areaField;
    
    private string phoneField;
    
    private string faxField;
    
    private string website_urlField;
    
    private string omf_file_urlField;
    
    private string logo_urlsField;
    
    private omfRestaurant_infoEnvironment environmentField;
    
    private string contactsField;
    
    private omfRestaurant_infoParent_company parent_companyField;
    
    /// <remarks/>
    public string restaurant_name {
        get {
            return this.restaurant_nameField;
        }
        set {
            this.restaurant_nameField = value;
        }
    }
    
    /// <remarks/>
    public string business_type {
        get {
            return this.business_typeField;
        }
        set {
            this.business_typeField = value;
        }
    }
    
    /// <remarks/>
    public object brief_description {
        get {
            return this.brief_descriptionField;
        }
        set {
            this.brief_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public object full_description {
        get {
            return this.full_descriptionField;
        }
        set {
            this.full_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public object location_id {
        get {
            return this.location_idField;
        }
        set {
            this.location_idField = value;
        }
    }
    
    /// <remarks/>
    public object mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    public object utc_offset {
        get {
            return this.utc_offsetField;
        }
        set {
            this.utc_offsetField = value;
        }
    }
    
    /// <remarks/>
    public string address_1 {
        get {
            return this.address_1Field;
        }
        set {
            this.address_1Field = value;
        }
    }
    
    /// <remarks/>
    public string address_2 {
        get {
            return this.address_2Field;
        }
        set {
            this.address_2Field = value;
        }
    }
    
    /// <remarks/>
    public string city_town {
        get {
            return this.city_townField;
        }
        set {
            this.city_townField = value;
        }
    }
    
    /// <remarks/>
    public string state_province {
        get {
            return this.state_provinceField;
        }
        set {
            this.state_provinceField = value;
        }
    }
    
    /// <remarks/>
    public ushort postal_code {
        get {
            return this.postal_codeField;
        }
        set {
            this.postal_codeField = value;
        }
    }
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public object region_area {
        get {
            return this.region_areaField;
        }
        set {
            this.region_areaField = value;
        }
    }
    
    /// <remarks/>
    public string phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string website_url {
        get {
            return this.website_urlField;
        }
        set {
            this.website_urlField = value;
        }
    }
    
    /// <remarks/>
    public string omf_file_url {
        get {
            return this.omf_file_urlField;
        }
        set {
            this.omf_file_urlField = value;
        }
    }
    
    /// <remarks/>
    public string logo_urls {
        get {
            return this.logo_urlsField;
        }
        set {
            this.logo_urlsField = value;
        }
    }
    
    /// <remarks/>
    public omfRestaurant_infoEnvironment environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    public string contacts {
        get {
            return this.contactsField;
        }
        set {
            this.contactsField = value;
        }
    }
    
    /// <remarks/>
    public omfRestaurant_infoParent_company parent_company {
        get {
            return this.parent_companyField;
        }
        set {
            this.parent_companyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfRestaurant_infoEnvironment {
    
    private object seating_qtyField;
    
    private object max_group_sizeField;
    
    private object age_level_preferenceField;
    
    private object smoking_allowedField;
    
    private object takeout_availableField;
    
    private omfRestaurant_infoEnvironmentDelivery_available delivery_availableField;
    
    private object catering_availableField;
    
    private object reservationsField;
    
    private object alcohol_typeField;
    
    private object music_typeField;
    
    private object pets_allowedField;
    
    private object wheelchair_accessibleField;
    
    private string dress_codeField;
    
    private string cuisine_type_primaryField;
    
    private object cuisine_type_secondaryField;
    
    private string seating_locationsField;
    
    private string accepted_currenciesField;
    
    private string online_reservationsField;
    
    private string online_orderingField;
    
    private omfRestaurant_infoEnvironmentOperating_day[] operating_daysField;
    
    private object parkingField;
    
    /// <remarks/>
    public object seating_qty {
        get {
            return this.seating_qtyField;
        }
        set {
            this.seating_qtyField = value;
        }
    }
    
    /// <remarks/>
    public object max_group_size {
        get {
            return this.max_group_sizeField;
        }
        set {
            this.max_group_sizeField = value;
        }
    }
    
    /// <remarks/>
    public object age_level_preference {
        get {
            return this.age_level_preferenceField;
        }
        set {
            this.age_level_preferenceField = value;
        }
    }
    
    /// <remarks/>
    public object smoking_allowed {
        get {
            return this.smoking_allowedField;
        }
        set {
            this.smoking_allowedField = value;
        }
    }
    
    /// <remarks/>
    public object takeout_available {
        get {
            return this.takeout_availableField;
        }
        set {
            this.takeout_availableField = value;
        }
    }
    
    /// <remarks/>
    public omfRestaurant_infoEnvironmentDelivery_available delivery_available {
        get {
            return this.delivery_availableField;
        }
        set {
            this.delivery_availableField = value;
        }
    }
    
    /// <remarks/>
    public object catering_available {
        get {
            return this.catering_availableField;
        }
        set {
            this.catering_availableField = value;
        }
    }
    
    /// <remarks/>
    public object reservations {
        get {
            return this.reservationsField;
        }
        set {
            this.reservationsField = value;
        }
    }
    
    /// <remarks/>
    public object alcohol_type {
        get {
            return this.alcohol_typeField;
        }
        set {
            this.alcohol_typeField = value;
        }
    }
    
    /// <remarks/>
    public object music_type {
        get {
            return this.music_typeField;
        }
        set {
            this.music_typeField = value;
        }
    }
    
    /// <remarks/>
    public object pets_allowed {
        get {
            return this.pets_allowedField;
        }
        set {
            this.pets_allowedField = value;
        }
    }
    
    /// <remarks/>
    public object wheelchair_accessible {
        get {
            return this.wheelchair_accessibleField;
        }
        set {
            this.wheelchair_accessibleField = value;
        }
    }
    
    /// <remarks/>
    public string dress_code {
        get {
            return this.dress_codeField;
        }
        set {
            this.dress_codeField = value;
        }
    }
    
    /// <remarks/>
    public string cuisine_type_primary {
        get {
            return this.cuisine_type_primaryField;
        }
        set {
            this.cuisine_type_primaryField = value;
        }
    }
    
    /// <remarks/>
    public object cuisine_type_secondary {
        get {
            return this.cuisine_type_secondaryField;
        }
        set {
            this.cuisine_type_secondaryField = value;
        }
    }
    
    /// <remarks/>
    public string seating_locations {
        get {
            return this.seating_locationsField;
        }
        set {
            this.seating_locationsField = value;
        }
    }
    
    /// <remarks/>
    public string accepted_currencies {
        get {
            return this.accepted_currenciesField;
        }
        set {
            this.accepted_currenciesField = value;
        }
    }
    
    /// <remarks/>
    public string online_reservations {
        get {
            return this.online_reservationsField;
        }
        set {
            this.online_reservationsField = value;
        }
    }
    
    /// <remarks/>
    public string online_ordering {
        get {
            return this.online_orderingField;
        }
        set {
            this.online_orderingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("operating_day", IsNullable=false)]
    public omfRestaurant_infoEnvironmentOperating_day[] operating_days {
        get {
            return this.operating_daysField;
        }
        set {
            this.operating_daysField = value;
        }
    }
    
    /// <remarks/>
    public object parking {
        get {
            return this.parkingField;
        }
        set {
            this.parkingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfRestaurant_infoEnvironmentDelivery_available {
    
    private string radiusField;
    
    private string feeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fee {
        get {
            return this.feeField;
        }
        set {
            this.feeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfRestaurant_infoEnvironmentOperating_day {
    
    private byte day_of_weekField;
    
    private string open_timeField;
    
    private string close_timeField;
    
    /// <remarks/>
    public byte day_of_week {
        get {
            return this.day_of_weekField;
        }
        set {
            this.day_of_weekField = value;
        }
    }
    
    /// <remarks/>
    public string open_time {
        get {
            return this.open_timeField;
        }
        set {
            this.open_timeField = value;
        }
    }
    
    /// <remarks/>
    public string close_time {
        get {
            return this.close_timeField;
        }
        set {
            this.close_timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfRestaurant_infoParent_company {
    
    private object parent_company_nameField;
    
    private object parent_company_websiteField;
    
    private object address_1Field;
    
    private object address_2Field;
    
    private object city_townField;
    
    private object state_provinceField;
    
    private object postal_codeField;
    
    private object countryField;
    
    private object phoneField;
    
    private object faxField;
    
    /// <remarks/>
    public object parent_company_name {
        get {
            return this.parent_company_nameField;
        }
        set {
            this.parent_company_nameField = value;
        }
    }
    
    /// <remarks/>
    public object parent_company_website {
        get {
            return this.parent_company_websiteField;
        }
        set {
            this.parent_company_websiteField = value;
        }
    }
    
    /// <remarks/>
    public object address_1 {
        get {
            return this.address_1Field;
        }
        set {
            this.address_1Field = value;
        }
    }
    
    /// <remarks/>
    public object address_2 {
        get {
            return this.address_2Field;
        }
        set {
            this.address_2Field = value;
        }
    }
    
    /// <remarks/>
    public object city_town {
        get {
            return this.city_townField;
        }
        set {
            this.city_townField = value;
        }
    }
    
    /// <remarks/>
    public object state_province {
        get {
            return this.state_provinceField;
        }
        set {
            this.state_provinceField = value;
        }
    }
    
    /// <remarks/>
    public object postal_code {
        get {
            return this.postal_codeField;
        }
        set {
            this.postal_codeField = value;
        }
    }
    
    /// <remarks/>
    public object country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    public object phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public object fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfMenu {
    
    private object menu_descriptionField;
    
    private object menu_noteField;
    
    private omfMenuMenu_duration menu_durationField;
    
    private omfMenuMenu_group[] menu_groupsField;
    
    private string nameField;
    
    private string currency_symbolField;
    
    private string languageField;
    
    private string uidField;
    
    /// <remarks/>
    public object menu_description {
        get {
            return this.menu_descriptionField;
        }
        set {
            this.menu_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public object menu_note {
        get {
            return this.menu_noteField;
        }
        set {
            this.menu_noteField = value;
        }
    }
    
    /// <remarks/>
    public omfMenuMenu_duration menu_duration {
        get {
            return this.menu_durationField;
        }
        set {
            this.menu_durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("menu_group", IsNullable=false)]
    public omfMenuMenu_group[] menu_groups {
        get {
            return this.menu_groupsField;
        }
        set {
            this.menu_groupsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency_symbol {
        get {
            return this.currency_symbolField;
        }
        set {
            this.currency_symbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfMenuMenu_duration {
    
    private object menu_duration_nameField;
    
    private object menu_duration_time_startField;
    
    private object menu_duration_time_endField;
    
    /// <remarks/>
    public object menu_duration_name {
        get {
            return this.menu_duration_nameField;
        }
        set {
            this.menu_duration_nameField = value;
        }
    }
    
    /// <remarks/>
    public object menu_duration_time_start {
        get {
            return this.menu_duration_time_startField;
        }
        set {
            this.menu_duration_time_startField = value;
        }
    }
    
    /// <remarks/>
    public object menu_duration_time_end {
        get {
            return this.menu_duration_time_endField;
        }
        set {
            this.menu_duration_time_endField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfMenuMenu_group {
    
    private object menu_group_descriptionField;
    
    private object menu_group_noteField;
    
    private omfMenuMenu_groupMenu_item[] menu_itemsField;
    
    private string nameField;
    
    private string uidField;
    
    /// <remarks/>
    public object menu_group_description {
        get {
            return this.menu_group_descriptionField;
        }
        set {
            this.menu_group_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public object menu_group_note {
        get {
            return this.menu_group_noteField;
        }
        set {
            this.menu_group_noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("menu_item", IsNullable=false)]
    public omfMenuMenu_groupMenu_item[] menu_items {
        get {
            return this.menu_itemsField;
        }
        set {
            this.menu_itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class omfMenuMenu_groupMenu_item {
    
    private string menu_item_nameField;
    
    private string menu_item_descriptionField;
    
    private string menu_item_priceField;
    
    private string uidField;
    
    /// <remarks/>
    public string menu_item_name {
        get {
            return this.menu_item_nameField;
        }
        set {
            this.menu_item_nameField = value;
        }
    }
    
    /// <remarks/>
    public string menu_item_description {
        get {
            return this.menu_item_descriptionField;
        }
        set {
            this.menu_item_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string menu_item_price {
        get {
            return this.menu_item_priceField;
        }
        set {
            this.menu_item_priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
}
