using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Microsoft.DPE.ReferenceApps.Food.Lib.Models
{
    public enum PriceRanges : int
    {
        Unknown = 0,
        From00To15 = 1,
        From15To30 = 2,
        From30To50 = 3,
        From50To75 = 4,
        From75ToUp = 5
    }

    public enum Cuisines
    {

        Afghan,
        American,
        Argentine,
        Asian,
        Austrian,
        Bagels,
        Bakery,
        Barbecue,
        Belgian,
        Bistro,
        Brazilian,
        British,
        Buffet,
        Burgers,
        Cafe,
        Cajun,
        Californian,
        Calzones,
        Cambodian,
        Caribbean,
        Catering,
        Cheesesteaks,
        Chicken,
        Chinese,
        Chowder,
        Coffee,
        Colombian,
        Contemporary,
        Continental,
        Creole,
        Crepes,
        Cuban,
        Czech,
        Deli,
        Dim_Sum,
        Diner,
        Dominican,
        Donuts,
        Eastern_European,
        Eclectic,
        English,
        Ethiopian,
        European,
        Fast_Food,
        Filipino,
        Fish_and_Chips,
        Fondue,
        French,
        Frozen_Yogurt,
        Fusion,
        Gastropub,
        German,
        Greek,
        Grill,
        Gyros,
        Haitian,
        Halal,
        Hawaiian,
        Healthy,
        Hookah_Bar,
        Hot_Dogs,
        Ice_Cream,
        Indian,
        Indonesian,
        International,
        Irish,
        Israeli,
        Italian,
        Japanese,
        Juices,
        Korean,
        Korean_Barbeque,
        Kosher,
        Latin,
        Latin_American,
        Lebanese,
        Malaysian,
        Mediterranean,
        Mexican,
        Middle_Eastern,
        Mongolian,
        Moroccan,
        Nepalese,
        Noodle_Bar,
        Norwegian,
        Organic,
        Oysters,
        Pacific_Rim,
        Pakistani,
        Pan_Asian,
        Pasta,
        Pastries,
        Persian,
        Peruvian,
        Pho,
        Pizza,
        Polish,
        Polynesian,
        Portuguese,
        Pub_Food,
        Puerto_Rican,
        Ribs,
        Salad,
        Salvadoran,
        Sandwiches,
        Seafood,
        Singaporean,
        Smoothies,
        Soul_Food,
        Soup,
        South_American,
        South_Pacific,
        Southern,
        Southwestern,
        Spanish,
        Steak,
        Subs,
        Sushi,
        Taiwanese,
        Tapas,
        Tea,
        Tex_Mex,
        Thai,
        Tibetan,
        Traditional,
        Turkish,
        Ukrainian,
        Vegan,
        Vegetarian,
        Venezuelan,
        Venusian,
        Vietnamese,
        Wings,
        Wraps
    }
}
